---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    k8s.kuboard.cn/displayName: 物流应用
  labels:
    k8s.kuboard.cn/layer: web
    k8s.kuboard.cn/name: lms-web-2
  name: lms-web-2
  namespace: middleground-tenant-free
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s.kuboard.cn/layer: web
      k8s.kuboard.cn/name: lms-web-2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s.kuboard.cn/layer: web
        k8s.kuboard.cn/name: lms-web-2
    spec:
      containers:
        - image: 'docker-registry.laihui.com/middleground/middleground-lms-web-2.0:dev_latest'
          imagePullPolicy: Always
          name: lms-web-2
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    k8s.kuboard.cn/layer: web
    k8s.kuboard.cn/name: lms-web-2
  name: lms-web-2
  namespace: middleground-tenant-free
spec:
  ipFamilyPolicy: SingleStack
  ports:
    - name: sjjpd3
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    k8s.kuboard.cn/layer: web
    k8s.kuboard.cn/name: lms-web-2
  sessionAffinity: None
  type: ClusterIP

